command: ['streamlit', 'run', 'app.py']

env:
  - name: 'STREAMLIT_GATHER_USAGE_STATS'
    value: 'false'
  - name: PGDATABASE
    value: 'databricks_postgres'
  - name: PGPORT
    value: '5432'
  - name: PGSSLMODE
    value: 'require'

